### ISSUE TITLE
Create Linux JMX Recipe

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#59] opened 2020-11-11 20:44 UTC
[ **Documentation:** https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration)

**Necessary Configuration:**

- **JMX Username:** Prompt user to enter
- **JMX Password:** Prompt user to enter
- **JMX Host:** Allow user to confirm default of localhost, or enter new
- **JMX Port** : Allow user to confirm default of 9999, or enter new
- IF user is using **Tomcat** based on process discovery data
  - Copy the tomcat-metrics.yml.sample file and name it tomcat-metrics.yml to enable
  - Output to the user `We have detected you are running Tomcat, the default tomcat-metrics config file has been copied to /etc/integrations.d. NOTE you may need to configure your tomcat JVM to receive JMX Data by setting appropriate CATALINA_OPTS. Please refer to your Tomcat documentation for additional details on how to enable JMX.`
- IF user is using **JBoss** based on process discovery data set **jmx\_remote** to true.
  - Prompt: We have detected JBoss on your system. _Would you like to enable the Jboss Connection Format (Y/N)_ If user selects Y then set jmx\_remote\_jboss\_standalone to true, otherwise set to false.
- Prompt: `Are you using SSL?(Y/N)` If YES
  - Prompt `Enter key store file path if applicable):`
  - Prompt `Enter key store password if applicable):`
  - Prompt `Enter trust store file path if applicable:`
  - Prompt `Enter trust store password if applicable:`

Based on these prompts set variables key\_store, key\_store\_password, trust\_store, trust\_store\_password in the config file accordingly.<br/><br/>This particular integration needs to be tested with tomcat, JBoss, and another generic Java service.

**For Logging:** Ensure that common log file directories/patterns & process name for JMX is populated in the beginning of the recipe.

Sheila 1/7/2021: CC needs to test JBoss, Tom Cat and generic java svc on each distro.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-53

**Comment by JakubKotkowiak** [comment] 2021-01-08 16:10
Regarding the third generic java svc that we have to test this integration with, is there one that you have in mind? Or should we search and pick one on our own?

**Comment by rishimukhop1** [comment] 2021-01-14 00:41
Let's try it with Jetty!

**Comment by JakubKotkowiak** [comment] 2021-01-19 14:24
hello @rishimukhop1,
It seems that SUSE is being problematic yet again. When we install both tomcat and jetty on the SUSE system it seems to be failing on validation attempts even though the services are running and we checked if we can connect to the server via JMX (and it seems to be opening the connection correctly). On the rest of the systems it's working as intended so we're unsure if we should keep trying to resolve this issue or move ahead for now while skipping SUSE integration. Any feedback would be appreciated.

**Comment by rishimukhop1** [comment] 2021-01-20 00:08
We agreed today that we can skip SUSE linux for all recipes for now, and we will list it as officially unsupported for the MVP. We can come back to SUSE at a later date.

**Comment by jbeveland27** [comment] 2021-01-21 23:23
Closed by https://github.com/newrelic/open-install-library/commit/abdbfb7baa96ee2c849c0e130458f7ff97ea2caf

**Closed by jbeveland27** 2021-01-21 23:23 UTC
Labels: MVP 0.1, size:M
