### ISSUE TITLE
Automated agent bundling for containerized applications

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/open-install-library#27] opened 2020-10-29 18:02 UTC
For containerized environments, and for language agents that require modifications to source code- customers typically "bundle" agents in within their application. This usually entails making changes to Dockerfiles in addition to modifying source code and dependencies for certain languages.

**Requirement Overview** : Provide capabilities to interrogate and modify a Dockerfile in order to bundle agents in with a containerized application through the new relic CLI. This tooling will need to be accompanied by CI platform specific guidance or an integration (if possible) to expose the NR license key in a secure manner.

<span data-href="#aha_body_data_start" data-read-only="true" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Acceptance Criteria: 
<span data-href="#aha_body_data_end" data-read-only="true" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-12

**Comment by jbeveland27** [comment] 2021-03-04 04:47
dupe of #28

**Closed by jbeveland27** 2021-03-04 04:47 UTC
